GET http://localhost:3000/api/v1/users

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "username":"Wayne",
    "name":"Wendy Namome",
    "email": "namomewendy@email.com"
}

###
GET http://localhost:3000/api/v1/users/37e88f43-71c9-4c87-9d42-73852752f3f2

###
PATCH http://localhost:3000/api/v1/users/37e88f43-71c9-4c87-9d42-73852752f3f2
Content-Type: application/json

{
    "username":"Solomon M"
}

###
DELETE http://localhost:3000/api/v1/users/e7fb060e-1f65-4dca-bb33-848b5b58dc1f

###
GET http://localhost:3000/api/v1/media

###
GET http://localhost:3000/api/v1/media/8efe6fa5-e498-4dab-9498-7e8235214ac3

###
POST http://localhost:3000/api/v1/media
Content-Type: application/json

{
    "medianame": "John Wick Chapter 4",
    "overview":"With the price on his head ever increasing, legendary hit man John Wick takes his fight against the High Table global as he seeks out the most powerful players in the underworld, from New York to Paris to Japan to Berlin.",
    "posterpath":"https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_FMjpg_UX1000_.jpg",
    "price":30000,
    "Userid":"37e88f43-71c9-4c87-9d42-73852752f3f2",
    "mediaTypeTypeid":"61c12cfa-5fc1-42a7-86f4-0e4408942dd7",
    "genreGenreid":"0affd248-b807-4c45-bbf2-c38d3d32f97a",
    "originOriginid":"7472f76f-0611-4834-9aef-9a165baed293"
}

###
PATCH http://localhost:3000/api/v1/media/8efe6fa5-e498-4dab-9498-7e8235214ac3
Content-Type: application/json

{
    "price":8000
}

###
DELETE  http://localhost:3000/api/v1/media/8efe6fa5-e498-4dab-9498-7e8235214ac3

###
POST http://localhost:3000/api/v1/origin
Content-Type: application/json

{
    "country": "UG", 
    "language": "Luo"
}

###
GET http://localhost:3000/api/v1/origin